
import java.sql.Connection;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAGAR
 */
public class EditDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditDetails
     */
    public EditDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      public boolean verifText(){
        if(txt_fullname.getText().equals("")||txt_username.getText().equals("")||txt_address.getText().equals("")
                
       ||txt_password.getText().equals("")||txt_contact.getText().equals(""))
        {
        JOptionPane.showMessageDialog(null,"one or more empty feilds");
        return false;}
        else
    return true;}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt_customerid = new javax.swing.JTextField();
        txt_fullname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_postcode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        combo_type = new javax.swing.JComboBox();
        txt_account = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Full Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        txt_customerid.setText(" ");
        getContentPane().add(txt_customerid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, 30));

        txt_fullname.setText(" ");
        getContentPane().add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 180, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Address");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, 30));

        txt_address.setText(" ");
        getContentPane().add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 180, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Past Code");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        txt_postcode.setText(" ");
        getContentPane().add(txt_postcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Contact No.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 20));

        txt_contact.setText(" ");
        getContentPane().add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 180, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Email");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txt_email.setText(" ");
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 180, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("User Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txt_username.setText(" ");
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 180, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, 30));

        txt_password.setText(" ");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 200, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("User Type");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));

        combo_type.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " Individual", "Organization", "Organizer" }));
        getContentPane().add(combo_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 200, 30));

        txt_account.setText(" ");
        txt_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_accountActionPerformed(evt);
            }
        });
        getContentPane().add(txt_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 200, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Account No.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 120, 30));

        btn_update.setBackground(new java.awt.Color(51, 51, 255));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/25118.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        getContentPane().add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, 130, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("User Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("View Profile");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/videoblocks-vintage-violin-on-mirror-in-space-and-clouds-motion-music-and-nature-concept-time-lapse_scp47yxfq_thumbnail-full06.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String full_name=txt_fullname.getText();
        String username=txt_username.getText();
        String address=txt_address.getText();
        String postcode = txt_postcode.getText();
        String contact=txt_contact.getText();
        String email =txt_email.getText();
        String password=txt_password.getText();
        String type=combo_type.getSelectedItem().toString();
        String account = txt_account.getText();

        if(verifText()){
            Connection con = MyConnection.getConnection();
            users1 u = new users1();
            u.insertedUpdateDeleteStudent('U', null, full_name, username, address,postcode,contact,email,password,type,account);
            Customer c = new Customer();
            c.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_accountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    public static javax.swing.JComboBox combo_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField txt_account;
    public static javax.swing.JTextField txt_address;
    public static javax.swing.JTextField txt_contact;
    public static javax.swing.JTextField txt_customerid;
    public static javax.swing.JTextField txt_email;
    public static javax.swing.JTextField txt_fullname;
    public static javax.swing.JTextField txt_password;
    public static javax.swing.JTextField txt_postcode;
    public static javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
