
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MAGAR
 */
public class ManageEvents extends javax.swing.JInternalFrame {
  Connection con = null;
   PreparedStatement ps = null;
   ResultSet rs = null;
   Orgarnizer og = new Orgarnizer();
    public ManageEvents() {
        initComponents();
        fillBandCombo();
        og.fillOrgarnizerJtable(EventsTable, "");
        txt_concertid.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   public boolean verifText(){
    if(txt_concertname.getText().equals("")||band_combo.getSelectedItem().equals("")
   ||txt_venue.getText().equals("")||txt_tickets.getText().equals("")||
            txt_description.getText().equals(""))
    {
    JOptionPane.showMessageDialog(null,"One or more empty feilds");
    return false;}
    else
    return true;}
   public void fillBandCombo(){
       con = MyConnection.getConnection();
       String name = "SELECT * From band";
      
      try {
          ps=con.prepareStatement(name);
          rs = ps.executeQuery();
          while(rs.next()){
              String bn = rs.getString("name");
              band_combo.addItem(bn);}
          }  catch (SQLException ex) {
          Logger.getLogger(ManageEvents.class.getName()).log(Level.SEVERE, null, ex);}
      }
   

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        txt_venue = new javax.swing.JTextField();
        txt_agent = new javax.swing.JTextField();
        txt_concertname = new javax.swing.JTextField();
        txt_date = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_description = new javax.swing.JTextArea();
        btn_view = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EventsTable = new javax.swing.JTable();
        txt_concertid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        band_combo = new javax.swing.JComboBox();
        promo_combo = new javax.swing.JComboBox();
        txt_tickets = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(860, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Manage Event");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 270, 40));

        txt_price.setText(" ");
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 170, 30));

        txt_venue.setText(" ");
        jPanel1.add(txt_venue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 170, 30));

        txt_agent.setText(" ");
        jPanel1.add(txt_agent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 30));

        txt_concertname.setText(" ");
        jPanel1.add(txt_concertname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 170, 30));

        txt_date.setText(" ");
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 170, 30));

        txt_description.setColumns(20);
        txt_description.setRows(5);
        jScrollPane1.setViewportView(txt_description);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 170, 50));

        btn_view.setBackground(new java.awt.Color(255, 51, 0));
        btn_view.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apple-88-512.png"))); // NOI18N
        btn_view.setText("View Concert");
        btn_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewActionPerformed(evt);
            }
        });
        jPanel1.add(btn_view, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 200, 40));

        btn_update.setBackground(new java.awt.Color(255, 51, 0));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/s-time-table.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 190, 40));

        btn_remove.setBackground(new java.awt.Color(255, 51, 0));
        btn_remove.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xc.PNG"))); // NOI18N
        btn_remove.setText("Remove Event");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 200, 40));

        jButton5.setBackground(new java.awt.Color(102, 153, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back-arrow-icon-vector-260nw-1323173810.png"))); // NOI18N
        jButton5.setText("  ");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Concert Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Concert Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Description");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jPanel4.setBackground(new java.awt.Color(240, 65, 12));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Agent");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Venue");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Price");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("No. of Ticket");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Date & Time");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Band Name");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Is Promoted");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel13)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, 380));

        EventsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "concert_name", "band", "agent", "venue", "price", "tickets", "date", "description", "is promoted", "orgarnizer"
            }
        ));
        EventsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EventsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EventsTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 570, 220));
        jPanel1.add(txt_concertid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Enter a value to search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 210, 30));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        jPanel1.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 170, -1));

        band_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        band_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                band_comboActionPerformed(evt);
            }
        });
        jPanel1.add(band_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, 30));

        promo_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "YES", "NO" }));
        jPanel1.add(promo_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 70, -1));
        jPanel1.add(txt_tickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 170, 30));

        jlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/d7yero8-a46174ef-a1bd-4fd1-9d61-64a8f499933f.jpg"))); // NOI18N
        jlabel.setText(" ");
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewActionPerformed
        // TODO add your handling code here:
        rs = og.viewdata();
        EventsTable.setModel(DbUtils.resultSetToTableModel(rs));

    }//GEN-LAST:event_btn_viewActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String concert_name=txt_concertname.getText();
       String band = band_combo.getSelectedItem().toString();
        String agent = txt_agent.getText();
        String venue=txt_venue.getText();
        int price = Integer.parseInt(txt_price.getText());
        int tickets=Integer.parseInt(txt_tickets.getText());
        String date=txt_date.getText();
        String description=txt_description.getText();
        String is_promoted = promo_combo.getSelectedItem().toString();
        if(verifText()){

            og.insertedUpdateDeleteStudent('U', null, concert_name, band, agent, venue, price, tickets, date, description, is_promoted,null);
            rs=og.viewdata();
            EventsTable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        txt_concertid.setText("");
        txt_concertname.setText("");
       band_combo.setSelectedItem("");
        txt_agent.setText("");
        txt_venue.setText("");
        txt_price.setText("");
        txt_tickets.setText("");
        txt_date.setText("");
        txt_description.setText("");
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
       String concert_name=txt_concertname.getText();
       String band = band_combo.getSelectedItem().toString();
        String agent = txt_agent.getText();
        String venue=txt_venue.getText();
        int price = Integer.parseInt(txt_price.getText());
        int tickets=Integer.parseInt(txt_tickets.getText());
        String date=txt_date.getText();
        String description=txt_description.getText();
        String is_promoted = promo_combo.getSelectedItem().toString();
        if(!concert_name.equals("")){

            og.insertedUpdateDeleteStudent('D', null, concert_name, band,agent,venue,price,tickets,date, description,is_promoted,null);
            rs=og.viewdata();
            EventsTable.setModel(DbUtils.resultSetToTableModel(rs));

        }
        txt_concertid.setText("");
        txt_concertname.setText("");
      band_combo.setSelectedItem("");
        txt_agent.setText("");
        txt_venue.setText("");
        txt_price.setText("");
        txt_tickets.setText("");
        txt_date.setText("");
        txt_description.setText("");

    }//GEN-LAST:event_btn_removeActionPerformed

    private void EventsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EventsTableMouseClicked
        // TODO add your handling code here:

        try{  DefaultTableModel model = (DefaultTableModel)EventsTable.getModel();

            //get the selected row index
            int selectedRowIndex = EventsTable.getSelectedRow();

            //set the selected row data into JLabels
            String concert_id =  model.getValueAt(selectedRowIndex, 0).toString();
            String concert_name =  model.getValueAt(selectedRowIndex, 1).toString();
            String band = model.getValueAt(selectedRowIndex, 2).toString();
            String agent = model.getValueAt(selectedRowIndex, 3).toString();
            String venue = model.getValueAt(selectedRowIndex, 4).toString();
            String price = model.getValueAt(selectedRowIndex, 5).toString();
            String tickets = model.getValueAt(selectedRowIndex, 6).toString();
            String date = model.getValueAt(selectedRowIndex, 7).toString();
            String description = model.getValueAt(selectedRowIndex, 8).toString();
            String promote = model.getValueAt(selectedRowIndex, 9).toString();

            txt_concertid.setText(concert_id);
            txt_concertname.setText(concert_name);
            band_combo.setSelectedItem(band);
            txt_agent.setText(agent);
            txt_venue.setText(venue);
            txt_price.setText(price);
            txt_tickets.setText(tickets);
            txt_date.setText(date);
            txt_description.setText(description);
            promo_combo.setSelectedItem(promote);

        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
            JOptionPane.showMessageDialog(null, "not connected");
        }
    }//GEN-LAST:event_EventsTableMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        EventsTable.setModel(new DefaultTableModel(null,new Object[]{"concert_id","concert_name","band","agent","venue","price","No.of tickets","date","is_promoted","description"}));
        og.fillOrgarnizerJtable(EventsTable, txt_search.getText());

    }//GEN-LAST:event_txt_searchKeyReleased

    private void band_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_band_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_band_comboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EventsTable;
    private javax.swing.JComboBox band_combo;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_view;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlabel;
    private javax.swing.JComboBox promo_combo;
    private javax.swing.JTextField txt_agent;
    private javax.swing.JTextField txt_concertid;
    private javax.swing.JTextField txt_concertname;
    private javax.swing.JTextField txt_date;
    private javax.swing.JTextArea txt_description;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_tickets;
    private javax.swing.JTextField txt_venue;
    // End of variables declaration//GEN-END:variables
}
